### ISSUE TITLE
Screen width

### ISSUE THREAD

**Issue by fredrikr** [DavidKinder/Windows-Frotz#20]
It seems that the screen width that is written into the Z-machine header (address 0x21) is the actual width % 256. This causes problems for a game or library that tries to adapt the content to the screen width, or judge if the game is even playable.

I can't find anything in the standard saying what the terp should do in this case. Setting the width to 255 may be the best, and most likely to work with existing games.

**Comment by DavidKinder** [comment]
Fixed by commit 5dfae7c88985432e2ab39d7762c537782a2ad432.
