### ISSUE TITLE
[Screen too narrow.] in Trinity

### ISSUE THREAD

**Issue by MegaMoses** [DavidKinder/Windows-Frotz#21]
Attempting to run any of the versions of Trinity found here (https://github.com/historicalsource/trinity) will cause a [Screen too narrow.] or similar message followed by a prompt to press any key to quit, making the game impossible to run.  Apparently Trinity requires 79 columns minimum, but I'm getting the error even with no margins on a modern monitor.  Not sure what the issue could be.

**Comment by DavidKinder** [comment]
A recent issue was reported (https://github.com/DavidKinder/Windows-Frotz/issues/20) pointing out that the way the interpreter passes the screen width to the game wraps around at 255 characters. It is possible that this is the issue causing problems here. Can you give me an idea of how wide your screen is, in pixels?

**Comment by MegaMoses** [comment]
2560px.  I usually run Frotz with a left margin of 4 and a right margin of 1836, if that helps, but I still run into this issue even with no margins at all.

**Comment by MegaMoses** [comment]
Actually, it looks like changing my font size from 12 to 11 seems to have fixed it, even with my large margins enabled.

**Comment by DavidKinder** [comment]
Attached is a build of the latest code, which has https://github.com/DavidKinder/Windows-Frotz/issues/20 fixed. I suspect this will fix the problem for you, if yes let me know and I'll make a new release available.
[Frotz.zip](https://github.com/DavidKinder/Windows-Frotz/files/8054390/Frotz.zip)

**Comment by DavidKinder** [comment]
It shouldn't be long, I just need to find the time to make the release. Probably early next week.

**Comment by MegaMoses** [comment]
Great to hear and thanks for your help!
