### ISSUE TITLE
Missing Transcript file (Windows 10)

### ISSUE THREAD

**Issue by Snaptags** [DavidKinder/Windows-Frotz#23]
The release notes mention a transcript file. Unfortunately I cannot find such a log file anywhere on my Windows 10 system. Do I have to enable it first?

I'd like to use the transcript file for auto mapping using Trizbort Interactive Fiction Mapper.

**Comment by DavidKinder** [comment]
Transcript files are usually enabled from within a game playing under Frotz, by entering "script" as a command.

**Comment by DavidKinder** [comment]
Fixed by commit https://github.com/DavidKinder/Windows-Frotz/commit/1dbab137351cd499bad0c43346d58ec980999013.
