### ISSUE TITLE
Frotz 1.24: cant set Fixed width font

### ISSUE THREAD

**Issue by milnak** [DavidKinder/Windows-Frotz#27]
windows 11.
start frotz and open ZSpec11.z6

go to options and change fix width font to cascadia mono.
hit ok
re-open zspec11.z6

pick "3" text styles. fixed width wont show as fixed width.

need to delete
HKEY_CURRENT_USER\Software\David Kinder\Frotz\Display ! Fixed Font Name
then reopen frotz to get a fixed width font back.

**Comment by DavidKinder** [comment]
Oops, fixed by commit 81616ec2761dc1d36d7b09730325dc57b77c3a75. New release made of release 1.25.
