### ISSUE TITLE
Windows-Frotz doesn't work under Wine properly

### ISSUE THREAD

**Issue by bodhi-baum** [DavidKinder/Windows-Frotz#28]
I tested Windows-Frotz here with a Linux Mint maschine and it does install and start ok, as well as the installer.exe as the standalone version.

It's also possible to select a game and load it into W-Frotz but after that you can't type in any commands or letters.

**Comment by DavidKinder** [comment]
Since it works fine on Windows (and has done back as far as Windows 95) I'm not sure there's anything I can do here, unless someone wants to debug the interpreter under Wine. This sounds more like an issue with Wine's compatibility than a problem in Windows Frotz.

**Comment by DavidKinder** [comment]
Thinking about this a bit more, I have one idea as to what the problem might be. But I've no way of testing under Wine. If I create a test build would you run it and check the results?

**Comment by bodhi-baum** [comment]
Sure.

**Comment by DavidKinder** [comment]
This build shows a dialog when a key is pressed with a game running, containing some (hopefully) useful information. Would you please try this and report what the poop-up dialog contains?
[Frotz.zip](https://github.com/DavidKinder/Windows-Frotz/files/13916629/Frotz.zip)

**Comment by bodhi-baum** [comment]
Hi David, I appologize first of all but have also good news. I had to reinstall my system and installed newest version of wine now, which is 9.0x atm and now everything works fine. 
But I think your afford will maybe payout in the future. For now I would close this as solved, ok?

**Comment by bodhi-baum** [comment]
Due to new wine version Windows-Frotz works here now.

**Comment by DavidKinder** [comment]
Good to hear it's now working, thanks for letting me know.
